#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Matlab on January 03, 2026 at 17:52:41.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[120];
extern c_float ldata[240];
extern c_float udata[240];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[120];
extern c_float Dinvscaling[120];
extern c_float Escaling[240];
extern c_float Einvscaling[240];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[360];
extern c_int linsys_solver_P[360];
extern c_float linsys_solver_bp[360];
extern c_float linsys_solver_sol[360];
extern c_float linsys_solver_rho_inv_vec[240];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[120];
extern c_float ysolution[240];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[240];
extern c_float work_rho_inv_vec[240];
extern c_float work_x[120];
extern c_float work_y[240];
extern c_float work_z[240];
extern c_float work_xz_tilde[360];
extern c_float work_x_prev[120];
extern c_float work_z_prev[240];
extern c_float work_Ax[240];
extern c_float work_Px[120];
extern c_float work_Aty[120];
extern c_float work_delta_y[240];
extern c_float work_Atdelta_y[120];
extern c_float work_delta_x[120];
extern c_float work_Pdelta_x[120];
extern c_float work_Adelta_x[240];
extern c_float work_D_temp[120];
extern c_float work_D_temp_A[120];
extern c_float work_E_temp[240];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
