#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Matlab on January 03, 2026 at 17:52:34.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[160];
extern c_float ldata[280];
extern c_float udata[280];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[160];
extern c_float Dinvscaling[160];
extern c_float Escaling[280];
extern c_float Einvscaling[280];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[440];
extern c_int linsys_solver_P[440];
extern c_float linsys_solver_bp[440];
extern c_float linsys_solver_sol[440];
extern c_float linsys_solver_rho_inv_vec[280];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[160];
extern c_float ysolution[280];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[280];
extern c_float work_rho_inv_vec[280];
extern c_float work_x[160];
extern c_float work_y[280];
extern c_float work_z[280];
extern c_float work_xz_tilde[440];
extern c_float work_x_prev[160];
extern c_float work_z_prev[280];
extern c_float work_Ax[280];
extern c_float work_Px[160];
extern c_float work_Aty[160];
extern c_float work_delta_y[280];
extern c_float work_Atdelta_y[160];
extern c_float work_delta_x[160];
extern c_float work_Pdelta_x[160];
extern c_float work_Adelta_x[280];
extern c_float work_D_temp[160];
extern c_float work_D_temp_A[160];
extern c_float work_E_temp[280];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
